language: python
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
python:
- 3.8.6
install:
- pip install -q pipenv codecov
- pipenv sync --dev
script:
- pipenv run flake8 --max-line-length=120 --ignore=W605,F401
- pipenv run pytest --cov=pysei
branches:
  only:
  - master
after_success:
- pipenv run codecov
